version: "3.3"

networks:
  wpaas:

services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.18
    restart: unless-stopped
    networks:
      - wpaas
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=NTMwYWRhYjQ3MTQ3OTRmOWRiOGU0NzNm
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /home/ubuntu/postgres_data:/var/lib/postgresql/data:Z

  backstage:
    container_name: backstage
    image: backstage:latest
    restart: unless-stopped
    networks:
      - wpaas
    ports:
      - 80:7007
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=NTMwYWRhYjQ3MTQ3OTRmOWRiOGU0NzNm
      - GITHUB_TOKEN=${GITHUB_TOKEN}
